apiVersion: v2
description: Run JMeter performance tests in Kubernetes cluster with Kangal
keywords:
  - kubernetes
  - jmeter
  - performance tests
  - tests runner
name: kangal
version: 2.0.11
home: https://github.com/hellofresh/kangal
icon: https://raw.githubusercontent.com/hellofresh/kangal/master/logo.svg
maintainers:
  - name: Kangal
    email: kangal@hellofresh.com
