apiVersion: v1
description: Run JMeter performance tests in Kubernetes cluster with Kangal
keywords:
  - kubernetes
  - jmeter
  - performance tests
  - tests runner
name: kangal
version: 1.1.1
home: https://github.com/hellofresh/kangal
icon: https://raw.githubusercontent.com/hellofresh/kangal/master/kangal_logo.svg
maintainers:
  - name: Kangal
    email: kangal@hellofresh.com
